server.port=8081
spring.application.name=gateway-server
eureka.client.service-url.defaultZone=http://localhost:9201/eureka/
spring.cloud.gateway.routes[0].id=microservice-produits
spring.cloud.gateway.routes[0].uri=lb://MICROSERVICE-PRODUITS
spring.cloud.gateway.routes[0].predicates[0]=Path=/microservice-produits/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/microservice-produits/(?<remaining>.*), /\${remaining}
spring.cloud.gateway.routes[1].id=microservice-commandes
spring.cloud.gateway.routes[1].uri=lb://MICROSERVICE-COMMANDES
spring.cloud.gateway.routes[1].predicates[0]=Path=/microservice-commandes/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/microservice-commandes/(?<remaining>.*), /\${remaining}
spring.cloud.gateway.routes[2].id=microservice-paiement
spring.cloud.gateway.routes[2].uri=lb://MICROSERVICE-PAIEMENT
spring.cloud.gateway.routes[2].predicates[0]=Path=/microservice-paiement/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/microservice-paiement/(?<remaining>.*), /\${remaining}
spring.main.allow-bean-definition-overriding=true
