server.port=9211
spring.application.name=microservice-produits

# Eureka
eureka.client.service-url.defaultZone=http://localhost:9201/eureka/
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

#Configurations PostgreSQL
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/db_produits
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Nos configurations
mes-configs.limitDeProduits=20
